# Generated by Django 3.1.4 on 2021-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20, null=True, verbose_name='Menu name')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_picture',
            field=models.ImageField(blank=True, null=True, upload_to='logoimages', verbose_name='Your Logo picture: File type: "jpg or png"'),
        ),
    ]
