# Generated by Django 3.1.4 on 2021-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Name and Surname')),
                ('about_us', models.CharField(max_length=200, null=True, verbose_name='About your talent')),
                ('about_prof', models.CharField(max_length=200, null=True, verbose_name='About your Proffession')),
                ('about_more', models.TextField(max_length=2500, null=True, verbose_name='About your skills write detail')),
                ('your_sign', models.ImageField(blank=True, null=True, upload_to='sign/', verbose_name='Your sign: File type: "jpg or png"')),
                ('your_picture', models.ImageField(blank=True, null=True, upload_to='picture/', verbose_name='Your picture: File type: "jpg or png"')),
                ('your_interest', models.CharField(max_length=255, null=True, verbose_name='About your hobbi Title')),
                ('your_interest_detail', models.TextField(max_length=2500, null=True, verbose_name='About your hobbi Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_interest', models.CharField(max_length=255, null=True, verbose_name='About your interest class for Feathericon class ')),
                ('your_interest_detail', models.CharField(max_length=55, null=True, verbose_name='About your interest skills')),
            ],
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_class',
            field=models.CharField(max_length=255, null=True, verbose_name='Social icon as Material Design Icons class'),
        ),
    ]
