# Generated by Django 3.1.4 on 2021-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210129_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='your_interest',
            new_name='your_hobbi',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='your_interest_detail',
            new_name='your_hobbi_detail',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='your_interest',
            new_name='your_interest_title',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_prof',
            field=models.CharField(max_length=200, null=True, verbose_name='About your Profession'),
        ),
    ]
