# Generated by Django 3.1.4 on 2021-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210129_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='resultbackground/', verbose_name='Your result background image: File type:  "jpg or png": Size 2000x800 pixels ')),
            ],
        ),
        migrations.CreateModel(
            name='ResultOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_class', models.CharField(max_length=200, null=True, verbose_name='Your result  class for Feathericon class')),
                ('result_total', models.IntegerField(max_length=100, null=True, verbose_name='Your total  result  number')),
                ('result_name', models.CharField(max_length=200, null=True, verbose_name='Your result name')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='your_picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/', verbose_name='Your picture: File type: "jpg or png" Size 600x786 pixels  '),
        ),
        migrations.AlterField(
            model_name='about',
            name='your_sign',
            field=models.ImageField(blank=True, null=True, upload_to='sign/', verbose_name='Your sign: File type:  "jpg or png": Size 182x57 pixels '),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_picture',
            field=models.ImageField(blank=True, null=True, upload_to='homeimages/', verbose_name='Your picture: File type: "jpg or png": Size 2000x1333 pixels'),
        ),
    ]
