# Generated by Django 3.1.4 on 2021-02-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210201_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_class', models.CharField(max_length=200, null=True, verbose_name='Your services  class for Feathericon class')),
                ('service_name', models.CharField(max_length=200, null=True, verbose_name='Your services name')),
                ('service_detail', models.TextField(max_length=2000, null=True, verbose_name='Your services  detail')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicesMain',
        ),
        migrations.AddField(
            model_name='resultoutcome',
            name='result_class',
            field=models.CharField(max_length=200, null=True, verbose_name='Your result  class for Feathericon class'),
        ),
    ]
