# Generated by Django 3.1.4 on 2021-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210201_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_part', models.CharField(max_length=255, null=True, verbose_name='Work participation')),
                ('work_part_detail', models.TextField(max_length=3000, null=True, verbose_name='Work participation detail')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_work', models.DateField(verbose_name='Begin work year')),
                ('end_work', models.DateField(verbose_name='Begin work year')),
            ],
        ),
    ]
