# Generated by Django 3.1.4 on 2021-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_workpart_workpartdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_profession', models.CharField(max_length=255, null=True, verbose_name='Add your Skills')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_expertise', models.CharField(max_length=255, null=True, verbose_name='Work epertise')),
                ('work_expertise_detail', models.TextField(max_length=255, null=True, verbose_name='Work epertise')),
            ],
        ),
        migrations.CreateModel(
            name='YourSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_skills_name', models.CharField(max_length=255, null=True, verbose_name='Skills Name')),
                ('your_knowledge', models.IntegerField(max_length=2, null=True, verbose_name='Skills Present')),
                ('your_skills', models.ManyToManyField(to='base.Profession', verbose_name='Plesa choice your Profession')),
            ],
        ),
    ]
