# Generated by Django 3.1.4 on 2021-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_workexpertise_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpartdetail',
            name='company_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='workpartdetail',
            name='name_skills',
            field=models.CharField(max_length=255, null=True, verbose_name='Your position in the company '),
        ),
        migrations.AlterField(
            model_name='workpartdetail',
            name='begin_work',
            field=models.DateField(verbose_name='Begin work date'),
        ),
        migrations.AlterField(
            model_name='workpartdetail',
            name='end_work',
            field=models.DateField(verbose_name='End work date'),
        ),
    ]
