# Generated by Django 3.1.4 on 2021-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_workpartdetail_complete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpartdetail',
            name='your_position',
            field=models.CharField(max_length=255, null=True, verbose_name='Your company position'),
        ),
    ]
