# Generated by Django 3.1.4 on 2021-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_workpartdetail_your_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultoutcome',
            name='result_total',
            field=models.IntegerField(null=True, verbose_name='Your total  result  number'),
        ),
        migrations.AlterField(
            model_name='yourskills',
            name='your_knowledge',
            field=models.IntegerField(null=True, verbose_name='Skills Present'),
        ),
    ]
